language: elixir
sudo: false
elixir: 1.4.0
otp_release: 19.1
matrix:
  include:
    - elixir: 1.2.6
      otp_release: 18.1
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
