language: elixir
sudo: false
matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
    - elixir: 1.7.3
      otp_release: 21.1
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
script:
  - if [[ `elixir -v` = *"1.7"* ]]; then mix format --check-formatted; fi
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
